# 꼭 spring 안에있어야함
spring:
  datasource:
    password: 1q2w3e4r
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 99ef65ab95cab91c35ee4d8aa1c1e98c #REST API 키

jwt:
  secret: nio70SPQ12YgHzG5hLsv16fZrU0teuLO5L6FIH3UlOlHGz55G/Rp40ukOuQ7rZPQCRCwzzuUKEGhral2ZziL0A==